### ISSUE TITLE
invalid API key

### ISSUE THREAD

**Issue by riush03** [Lazzzer/llm-structurizer#41]
When i try to use this with the fronted am getting this error invalid API key. How can it be solved?
<img width="768" alt="Screenshot_1" src="https://github.com/Lazzzer/llm-structurizer/assets/55490860/414b18f5-fc8b-4fb3-ac16-691e384a700a">
<img width="733" alt="Screenshot_2" src="https://github.com/Lazzzer/llm-structurizer/assets/55490860/c73ff08f-c1c0-4f7a-8660-6f9b41a6f60a">

**Comment by Lazzzer** [comment]
Hello, thank you for exploring my project!

If you have successfully seeded your llm-structurizer database using the command `npx prisma db seed`, you will find a valid key in the `API_KEY` table. You just need to copy the value from the `id` field into your frontend .env file and you should be good to go.

**Comment by riush03** [comment]
Thank you, I will check it out.
